version: '3'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=ThisIsNotSecure
      - MINIO_SECRET_KEY=ThisIsNotSecure
    volumes:
      - 'minio_data:/data'
  imgproxy:
    image: darthsim/imgproxy
    depends_on:
      - minio
    environment:
      - IMGPROXY_KEY=623ec68503698935
      - IMGPROXY_SALT=fd4857fbc0dd8954
      - IMGPROXY_PNG_INTERLACED=true
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_QUALITY=60
      - IMGPROXY_USE_S3=true
      - IMGPROXY_S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=ThisIsNotSecure
      - AWS_SECRET_ACCESS_KEY=ThisIsNotSecure
    ports:
      - 8080:8080
  app:
    build: .
    depends_on:
      - db
      - minio
      - imgproxy
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=ThisIsNotSecure
      - DATABASE_URL=psql://user@db/database
      - S3_ENABLED=True
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=ThisIsNotSecure
      - S3_SECRET_KEY=ThisIsNotSecure
      - S3_BUCKET_NAME=media
      - IMGPROXY_PROTOCOL=s3
      - IMGPROXY_BUCKET_NAME=media
      - IMGPROXY_KEY=623ec68503698935
      - IMGPROXY_SALT=fd4857fbc0dd8954
      - IMGPROXY_HOST=http://localhost:8080

volumes:
  db_data: {}
  minio_data: {}
